// Auto-generated by test_coverage. Do not edit by hand.
// Consider adding this file to your .gitignore.

import 'core/definition/bean_definition_test.dart' as core_definition_bean_definition_test;
import 'core/definition/properties_test.dart' as core_definition_properties_test;
import 'core/definition_parameters_test.dart' as core_definition_parameters_test;
import 'core/instance/definition_instance_test.dart' as core_instance_definition_instance_test;
import 'core/qualifier_test.dart' as core_qualifier_test;
import 'measure_test.dart' as measure_test;
import 'module_test.dart' as module_test;

void main() {
  module_test.main();
  core_definition_bean_definition_test.main();
  core_definition_properties_test.main();
  core_instance_definition_instance_test.main();
  core_definition_parameters_test.main();
  core_qualifier_test.main();
  measure_test.main();
}
